require('dotenv').config();
const express = require('express');
const cors = require('cors');
const authRoutes = require('./routes/auth');
const productRoutes = require('./routes/products');
const cartRoutes = require('./routes/cart');
const app = express();
const logRequest = require('./middleware/logger');
const connectMongo = require('./mongo/connection');
const categoryRoutes = require('./routes/categories');
const reviewRoutes = require('./routes/reviews');
const statsRoutes = require('./routes/stats');
connectMongo();

app.use(cors());
app.use(express.json());
app.use(logRequest);
app.use('/api/auth', authRoutes);
app.use('/api/products', productRoutes);
app.use('/api/cart', cartRoutes);
app.use('/uploads', express.static('uploads'));
app.use('/api/categories', categoryRoutes);
app.use('/api/reviews', reviewRoutes);
app.use('/api/stats', statsRoutes);
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));